# Site settings
description: A blog about Elahe Jalalpour
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://elahejalalpour.github.io" # the base hostname & protocol for your site 

# User settings
username: Elahe Jalalpour
user_description: 
user_title: 
email: el.jalalpour@gmail.com
twitter_username: elahejalalpoor
github_username:  elahejalalpour
gplus_username:  el.jalalpour
disqus_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
